# -*- coding: utf-8 -*-
"""
Danh sách định nghĩa toàn bộ Test Cases của 4 module:
- Arithmetic (TC-ARITH-001 -> 025)
- Concatenate (TC-CONCAT-001 -> 011)
- Clear (TC-CLEAR-001 -> 015)
- Input Validation (TC-VALIDATE-001 -> 007)
"""

ALL_TEST_CASES = [
    # =========================================================================
    # MODULE: ARITHMETIC (25 test cases)
    # =========================================================================
    {
        "id": "TC-ARITH-001",
        "module": "Arithmetic",
        "title": "Cộng hai số nguyên dương",
        "num1": "25",
        "num2": "15",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "40",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-002",
        "module": "Arithmetic",
        "title": "Cộng số nguyên âm với số nguyên dương",
        "num1": "-30",
        "num2": "18",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "-12",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-003",
        "module": "Arithmetic",
        "title": "Cộng hai số thập phân (số thực)",
        "num1": "12.34",
        "num2": "5.66",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "18",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-004",
        "module": "Arithmetic",
        "title": "Cộng với số 0 (Phần tử trung hòa)",
        "num1": "0",
        "num2": "99",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "99",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-005",
        "module": "Arithmetic",
        "title": "Trừ hai số nguyên dương cho kết quả dương",
        "num1": "50",
        "num2": "20",
        "operation": "Subtract",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "30",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-006",
        "module": "Arithmetic",
        "title": "Trừ hai số cho kết quả số âm",
        "num1": "15",
        "num2": "40",
        "operation": "Subtract",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "-25",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-007",
        "module": "Arithmetic",
        "title": "Trừ hai số thập phân",
        "num1": "10.75",
        "num2": "3.25",
        "operation": "Subtract",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "7.5",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-008",
        "module": "Arithmetic",
        "title": "Trừ hai số bằng nhau cho kết quả bằng 0",
        "num1": "100",
        "num2": "100",
        "operation": "Subtract",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "0",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-009",
        "module": "Arithmetic",
        "title": "Nhân hai số nguyên dương",
        "num1": "12",
        "num2": "8",
        "operation": "Multiply",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "96",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-010",
        "module": "Arithmetic",
        "title": "Nhân số dương với số âm",
        "num1": "7",
        "num2": "-6",
        "operation": "Multiply",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "-42",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-011",
        "module": "Arithmetic",
        "title": "Nhân với số 0 (Phần tử hấp thụ)",
        "num1": "12345",
        "num2": "0",
        "operation": "Multiply",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "0",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-012",
        "module": "Arithmetic",
        "title": "Nhân hai số thập phân",
        "num1": "2.5",
        "num2": "4.2",
        "operation": "Multiply",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "10.5",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-013",
        "module": "Arithmetic",
        "title": "Chia hết hai số nguyên dương (kết quả nguyên)",
        "num1": "80",
        "num2": "4",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "20",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-014",
        "module": "Arithmetic",
        "title": "Chia không hết cho kết quả số thập phân",
        "num1": "7",
        "num2": "2",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "3.5",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-015",
        "module": "Arithmetic",
        "title": "Chia cho số 0 (Xử lý lỗi Divide by zero)",
        "num1": "100",
        "num2": "0",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Divide by zero error!",
    },
    {
        "id": "TC-ARITH-016",
        "module": "Arithmetic",
        "title": "Chia số 0 cho một số khác 0",
        "num1": "0",
        "num2": "25",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "0",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-017",
        "module": "Arithmetic",
        "title": "Chia hai số âm cho kết quả dương",
        "num1": "-50",
        "num2": "-5",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "10",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-018",
        "module": "Arithmetic",
        "title": "Tích chọn Integers only để lấy phần nguyên phép chia",
        "num1": "10",
        "num2": "3",
        "operation": "Divide",
        "integers_only": True,
        "action": "calculate",
        "expected_answer": "3",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-019",
        "module": "Arithmetic",
        "title": "Chuyển đổi trạng thái (Toggle) checkbox Integers only",
        "num1": "7",
        "num2": "2",
        "operation": "Divide",
        "integers_only": True,
        "action": "toggle_int_after",
        "expected_answer": "3.5",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-020",
        "module": "Arithmetic",
        "title": "Tích chọn Integers only với số âm thập phân",
        "num1": "-11",
        "num2": "2",
        "operation": "Divide",
        "integers_only": True,
        "action": "calculate",
        "expected_answer": "-5",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-021",
        "module": "Arithmetic",
        "title": "First number chứa ký tự không phải số trong phép tính số học",
        "num1": "abc",
        "num2": "10",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 1 is not a number",
    },
    {
        "id": "TC-ARITH-022",
        "module": "Arithmetic",
        "title": "Second number chứa ký tự không phải số trong phép tính số học",
        "num1": "50",
        "num2": "@#xyz",
        "operation": "Subtract",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 2 is not a number",
    },
    {
        "id": "TC-ARITH-023",
        "module": "Arithmetic",
        "title": "Để trống cả hai trường số khi thực hiện phép tính số học",
        "num1": "",
        "num2": "",
        "operation": "Multiply",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "0",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-024",
        "module": "Arithmetic",
        "title": "Nhập số đạt giới hạn độ dài tối đa 10 ký tự",
        "num1": "1234567890",
        "num2": "1",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "1234567891",
        "expected_error": "",
    },
    {
        "id": "TC-ARITH-025",
        "module": "Arithmetic",
        "title": "Nhấn nút Clear để xóa kết quả phép tính và đặt lại trạng thái",
        "num1": "25",
        "num2": "25",
        "operation": "Add",
        "integers_only": True,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },

    # =========================================================================
    # MODULE: CONCATENATE (11 test cases)
    # =========================================================================
    {
        "id": "TC-CONCAT-001",
        "module": "Concatenate",
        "title": "Nối hai chuỗi chữ thông thường",
        "num1": "Hello",
        "num2": "World",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "HelloWorld",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-002",
        "module": "Concatenate",
        "title": "Nối hai giá trị số",
        "num1": "123",
        "num2": "456",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "123456",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-003",
        "module": "Concatenate",
        "title": "First number rỗng, Second number có giá trị",
        "num1": "",
        "num2": "World",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "World",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-004",
        "module": "Concatenate",
        "title": "First number có giá trị, Second number rỗng",
        "num1": "Hello",
        "num2": "",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "Hello",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-005",
        "module": "Concatenate",
        "title": "Cả hai đầu vào đều rỗng",
        "num1": "",
        "num2": "",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-006",
        "module": "Concatenate",
        "title": "Nối chuỗi chứa ký tự đặc biệt",
        "num1": "user@",
        "num2": "test.com",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "user@test.com",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-007",
        "module": "Concatenate",
        "title": "Nối chuỗi có khoảng trắng",
        "num1": "Good ",
        "num2": "Morning",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "Good Morning",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-008",
        "module": "Concatenate",
        "title": "Nối chuỗi chữ hoa và chữ thường",
        "num1": "ABC",
        "num2": "def",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "ABCdef",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-009",
        "module": "Concatenate",
        "title": "Nối hai số thập phân dạng chuỗi",
        "num1": "3.14",
        "num2": "2.71",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "3.142.71",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-010",
        "module": "Concatenate",
        "title": "Nối chuỗi chứa số âm",
        "num1": "-50",
        "num2": "-20",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "-50-20",
        "expected_error": "",
    },
    {
        "id": "TC-CONCAT-011",
        "module": "Concatenate",
        "title": "Nối hai chuỗi giống nhau",
        "num1": "Test",
        "num2": "Test",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "TestTest",
        "expected_error": "",
    },

    # =========================================================================
    # MODULE: CLEAR (15 test cases)
    # =========================================================================
    {
        "id": "TC-CLEAR-001",
        "module": "Clear",
        "title": "Clear sau khi nhập đầy đủ dữ liệu và tính toán",
        "num1": "10",
        "num2": "5",
        "operation": "Add",
        "integers_only": True,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-002",
        "module": "Clear",
        "title": "Clear khi chỉ nhập First Number (chưa tính toán)",
        "num1": "123",
        "num2": "",
        "operation": "Add",
        "integers_only": False,
        "action": "just_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-003",
        "module": "Clear",
        "title": "Clear khi chỉ nhập Second Number (chưa tính toán)",
        "num1": "",
        "num2": "456",
        "operation": "Add",
        "integers_only": False,
        "action": "just_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-004",
        "module": "Clear",
        "title": "Clear khi tất cả các trường đang trống",
        "num1": "",
        "num2": "",
        "operation": "Add",
        "integers_only": False,
        "action": "just_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-005",
        "module": "Clear",
        "title": "Clear sau khi nhập input không hợp lệ",
        "num1": "abc",
        "num2": "def",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-006",
        "module": "Clear",
        "title": "Clear sau khi thực hiện phép chia cho 0",
        "num1": "10",
        "num2": "0",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-007",
        "module": "Clear",
        "title": "Clear sau khi thực hiện phép tính Concatenate",
        "num1": "Hello",
        "num2": "World",
        "operation": "Concatenate",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-008",
        "module": "Clear",
        "title": "Clear khi checkbox Integers only đang được bật",
        "num1": "10",
        "num2": "3",
        "operation": "Divide",
        "integers_only": True,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-009",
        "module": "Clear",
        "title": "Clear nhiều lần liên tiếp",
        "num1": "50",
        "num2": "50",
        "operation": "Add",
        "integers_only": False,
        "action": "clear_multiple_times",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-010",
        "module": "Clear",
        "title": "Clear sau khi tính toán xong, sau đó tính tiếp bình thường",
        "num1": "10",
        "num2": "20",
        "operation": "Add",
        "integers_only": False,
        "action": "clear_then_recalculate",
        "expected_answer": "40",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-011",
        "module": "Clear",
        "title": "Clear sau khi nhập số âm vào cả hai trường",
        "num1": "-15",
        "num2": "-35",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-012",
        "module": "Clear",
        "title": "Clear sau khi nhập số thập phân",
        "num1": "3.14",
        "num2": "2.86",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-013",
        "module": "Clear",
        "title": "Clear khi đang chọn Build khác Prototype",
        "num1": "10",
        "num2": "20",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-014",
        "module": "Clear",
        "title": "Clear sau khi nhập số rất lớn",
        "num1": "9999999999",
        "num2": "8888888888",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },
    {
        "id": "TC-CLEAR-015",
        "module": "Clear",
        "title": "Clear khi ô Answer đang hiển thị kết quả thập phân",
        "num1": "7",
        "num2": "2",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate_then_clear",
        "expected_answer": "",
        "expected_error": "",
    },

    # =========================================================================
    # MODULE: INPUT VALIDATION (7 test cases)
    # =========================================================================
    {
        "id": "TC-VALIDATE-001",
        "module": "Input Validation",
        "title": "Bỏ trống cả hai trường dữ liệu đầu vào",
        "num1": "",
        "num2": "",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 1 is not a number",
    },
    {
        "id": "TC-VALIDATE-002",
        "module": "Input Validation",
        "title": "Bỏ trống trường First number khi thực hiện phép tính số học",
        "num1": "",
        "num2": "10",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 1 is not a number",
    },
    {
        "id": "TC-VALIDATE-003",
        "module": "Input Validation",
        "title": "Bỏ trống trường Second number khi thực hiện phép tính số học",
        "num1": "10",
        "num2": "",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 2 is not a number",
    },
    {
        "id": "TC-VALIDATE-004",
        "module": "Input Validation",
        "title": "Nhập chữ cái (Alphabet) vào trường số",
        "num1": "abc",
        "num2": "15",
        "operation": "Multiply",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 1 is not a number",
    },
    {
        "id": "TC-VALIDATE-005",
        "module": "Input Validation",
        "title": "Nhập ký tự đặc biệt vào trường số",
        "num1": "10",
        "num2": "@#$%",
        "operation": "Divide",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 2 is not a number",
    },
    {
        "id": "TC-VALIDATE-006",
        "module": "Input Validation",
        "title": "Nhập chuỗi chỉ chứa khoảng trắng vào trường số",
        "num1": "   ",
        "num2": "20",
        "operation": "Subtract",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "",
        "expected_error": "Number 1 is not a number",
    },
    {
        "id": "TC-VALIDATE-007",
        "module": "Input Validation",
        "title": "Kiểm tra dữ liệu hợp lệ (Số nguyên và số thực)",
        "num1": "12.5",
        "num2": "2.5",
        "operation": "Add",
        "integers_only": False,
        "action": "calculate",
        "expected_answer": "15",
        "expected_error": "",
    },
]
